### ISSUE TITLE
Dropdown items are not visible

### ISSUE THREAD

**Issue by amarjeet000** [fulcro-legacy/semantic-ui-wrapper#1]
I created a dropdown with the folloiwng code:

```
(def dropdown-options #js [{:key "a" :value "1" :text "Text1"}
                           {:key "b" :value "2" :text "Text2"}])

(defn resource-selector
  []
  (s/ui-dropdown #js {:search true
                      :scrolling true
                      :selection true
                      :placeholder "Select resources"
                      :options dropdown-options}))
```

Expected result:
1. Menu should open on click and items should be visible
2. After selecting an item, the placeholder should be replaced by the item text.

Actual result:
1. Menu opens, but item texts are not visible - just sections are visible.
2. Nothing happens to placeholder even if I try to select a section (with invisible text)

Any ideas what I am doing wrong?

**Comment by awkay** [comment]
Sorry I don't. These are super-thin wrappers (and I don't use them, I put them out there as a starting point for others to use and contrubute to). The pass through to semantic-ui-react. See their docs.

**Comment by amarjeet000** [comment]
No problem. Hopefully, will be able to contribute in future. I am using it in my project.
