### ISSUE TITLE
shadow-cljs compile error

### ISSUE THREAD

**Issue by vixns** [fulcro-legacy/semantic-ui-wrapper#2]
`lein new fulcro test-project && cd  test-project`

`npx shadow-cljs watch cards` => ok

add `[cljsjs/semantic-ui-react "0.78.2-0"]` and `[fulcrologic/semantic-ui-react-wrappers "1.0.0"]`to project dependencies
require  `[fulcrologic.semantic-ui.factories :as f]` in  components.cljc

run npx shadow-cljs watch cards =>

The required namespace "cljsjs.semantic-ui-react" is not available, it was required by "fulcrologic/semantic_ui/factories.cljc".

**Comment by awkay** [comment]
You probably need to exclude the cljsjs semantic, and use package.json. Shadow-cljs does not support cljsjs, and it seems to not have a patch to make that one transparent.

**Comment by awkay** [comment]
See https://code.thheller.com/blog/shadow-cljs/2017/11/10/js-dependencies-in-practice.html
